name: design_patern_and_principle
description: "Design pattern and Principle Flutter"

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  syntax_highlight: ^0.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true